version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: deploy/Dockerfile.app
    environment:
      CONFIG_ARTICLES_DSN: postgres://conduit:conduit@postgres/conduit?sslmode=disable
      CONFIG_USERS_DSN: postgres://conduit:conduit@postgres/conduit?sslmode=disable
    ports:
      - 8080:8080

  postgres:
    image: postgres:10-alpine
    restart: always
    environment:
      POSTGRES_USER: conduit
      POSTGRES_PASSWORD: conduit
      POSTGRES_DB: conduit
    ports:
      - 5432:5432

  migration:
    build:
      context: .
      dockerfile: deploy/Dockerfile.migrate-wait-for
    volumes:
      - type: bind
        source: ./migrations
        target: /migrations/
    command:
      - "-verbose"
      - "-path=/migrations/"
      - "-database=postgresql://conduit:conduit@postgres/conduit?sslmode=disable"
      - "up"
    depends_on:
      - postgres
