CREATE TABLE IF NOT EXISTS users (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text UNIQUE NOT NULL,
    name text UNIQUE NOT NULL,
    bio text,
    image text, -- base64
    password_hash text NOT NULL
);

CREATE INDEX users_email_idx ON users (email);

CREATE TABLE IF NOT EXISTS articles (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug text UNIQUE NOT NULL,
    title text NOT NULL,
    description text,
    body text,
    created timestamptz NOT NULL DEFAULT NOW(),
    updated timestamptz NOT NULL DEFAULT NOW(),
    author_id int NOT NULL REFERENCES users (id) 
);

CREATE INDEX articles_slug_idx ON articles (slug);
